# Archivos y DataFrames

## Archivos de texto

### <font color = 'green'>Librería estandar de Python

#### Lectura de archivos

In [ ]:
s_1 = open ('texto_1.txt').read()
print(s_1)

In [ ]:
s_1

In [ ]:
# Cargar en una lista línea por línea:
lineas = [linea.strip() for linea in open('texto_1.txt')]
print (lineas)

In [ ]:
texto = open('texto_1.txt','r')
lineas_1 = texto.readlines()
print (lineas_1)

In [2]:
# Ejemplo quiz autocalificable
# Carga de datos

preguntas = [linea.strip() for linea in open('preguntas.txt')]
respuestas = [linea.strip() for linea in open('respuestas.txt')]

# Inicialización de variables:
aciertos= 0

# Procesos:

for i in range(len(preguntas)):
    resp = input(preguntas[i] + '\n')
    if resp.lower() == respuestas[i].lower():
        print('\n¡Correcto!')
        aciertos+= 1
    else:
        print('\ERROR: la respuesta correcta es:', respuestas [i])
    print('\nLleva',aciertos, 'aciertos de', i+1)
    print('_'*25, '\n')
    
# Salidas
print ('\n Su Nota final es %.1f' % (float(aciertos)*5/len(preguntas)))

¿En Python las tuplas se pueden modificar? Si/No
no

¡Correcto!

Lleva 1 aciertos de 1
_________________________ 

¿Cuál es el código en Python para añadir 5 como elemento al final de la lista L?
ww
\ERROR: la respuesta correcta es: L.append(5)

Lleva 1 aciertos de 2
_________________________ 

¿Cómo se determina en Python el tamaño de la matriz M usando un método?

\ERROR: la respuesta correcta es: M.shape

Lleva 1 aciertos de 3
_________________________ 

¿Cómo se determina en Python el tamaño de la matriz M usando una función?

\ERROR: la respuesta correcta es: np.shape(M)

Lleva 1 aciertos de 4
_________________________ 

¿Cuál símbolo se usa en pseudocódigo para concatenar cadenas de caracteres?

\ERROR: la respuesta correcta es: &

Lleva 1 aciertos de 5
_________________________ 

¿Cuál es el operador en Python para elevar a un exponente?

\ERROR: la respuesta correcta es: **

Lleva 1 aciertos de 6
_________________________ 


 Su Nota final es 0.8


#### Escritura o creación

In [6]:
# Crear un archivo nuevo:
f = open('archivo_escritura.txt', 'w') #w : write

# Se escribe línea a línea:
print('Esta es la línea 1.', file = f)
print('Esta es la línea 2.', file = f)
f.close()

In [7]:
poema = ''' Esto es amor
Esto es el amor: llevar en la sangre

el impulso inefable de otra sangre,

buscarse el corazón dentro del pecho

y no encontrarlo hasta palpar su frente,

padecer la ansiedad de ser en otro

como grano de trigo germinando,

es trasladar el mar hasta sus ojos

y sumergirse en ellos hasta el alma,

sentir la eternidad entre las manos

al descubrir a Dios en su mirada,

árbol del  bien que las horas traspasa.

Esto es amor: ser uno proyectado.


'''
f = open('poema_esto_es_amor.txt','w')

# Se escribe el archivo completo de una vez:
print(poema, file = f)
f.close()

In [9]:
f = open ('poema_esto_es_amor.txt','r')
f.readlines()

[' Esto es amor\n',
 'Esto es el amor: llevar en la sangre\n',
 '\n',
 'el impulso inefable de otra sangre,\n',
 '\n',
 'buscarse el corazón dentro del pecho\n',
 '\n',
 'y no encontrarlo hasta palpar su frente,\n',
 '\n',
 'padecer la ansiedad de ser en otro\n',
 '\n',
 'como grano de trigo germinando,\n',
 '\n',
 'es trasladar el mar hasta sus ojos\n',
 '\n',
 'y sumergirse en ellos hasta el alma,\n',
 '\n',
 'sentir la eternidad entre las manos\n',
 '\n',
 'al descubrir a Dios en su mirada,\n',
 '\n',
 'árbol del  bien que las horas traspasa.\n',
 '\n',
 'Esto es amor: ser uno proyectado.\n',
 '\n',
 '\n',
 '\n']

In [12]:
# Ejmplo: conversión de unidades de temeratura entre grados centrírados y fahrenheit:
# Carga de datos:
temp_C = [linea.strip() for linea in open('Temp_c.txt')]

# Conversión de unidades:
arch_1 =open('Temp_F.txt', 'w')
for T_C in temp_C:
    T_F = round(float(T_C)* (9/5) + 32, ndigits = 1)
    print(T_F, file = arch_1)
arch_1.close()
    

### <font color = 'green'>Librería Numpy

In [13]:
# Importación de la librería
import numpy as np

In [15]:
#np.savetxt y np.loadtxt
m_1 = np.random.random ((10,19))
np.savetxt('archivo_m_1.txt', m_1, fmt ='%.2f', delimiter ='\t')

In [16]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [17]:
m_2 = np.loadtxt('archivo_m_1.txt')
m_2

array([[0.33, 0.01, 0.08, 0.68, 0.21, 0.98, 0.72, 0.64, 0.3 , 0.3 , 0.58,
        0.56, 0.85, 0.59, 0.02, 0.18, 0.14, 0.41, 0.54],
       [0.86, 0.24, 0.49, 0.94, 0.71, 0.04, 0.37, 0.55, 0.72, 0.14, 0.16,
        0.6 , 0.45, 0.77, 0.98, 0.65, 0.03, 0.56, 0.86],
       [0.56, 0.59, 0.02, 0.35, 0.15, 0.44, 0.81, 0.23, 0.93, 0.65, 0.66,
        0.09, 0.52, 0.98, 0.78, 0.22, 0.15, 0.15, 0.39],
       [0.55, 0.07, 0.01, 0.97, 0.21, 0.28, 0.53, 0.89, 0.26, 0.88, 0.46,
        0.5 , 0.54, 0.66, 0.45, 0.61, 0.86, 0.04, 0.05],
       [0.25, 0.2 , 0.26, 0.68, 0.8 , 0.59, 0.5 , 0.51, 0.4 , 0.83, 0.33,
        0.84, 0.98, 0.06, 0.17, 0.14, 0.02, 0.42, 0.94],
       [0.11, 0.33, 0.1 , 0.9 , 0.01, 0.92, 0.26, 0.43, 0.38, 0.62, 0.96,
        0.74, 0.42, 0.03, 0.44, 0.75, 0.56, 0.4 , 0.66],
       [0.68, 0.97, 0.31, 0.89, 0.68, 0.6 , 0.92, 0.77, 0.59, 0.48, 0.67,
        0.16, 0.44, 0.2 , 0.11, 0.06, 0.02, 0.31, 0.88],
       [0.74, 0.39, 0.79, 0.18, 0.56, 0.36, 0.67, 0.35, 0.39, 0.85, 0.22,
        0

In [18]:
m_1 == m_2

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, Fa

In [19]:
m_1


array([[0.32782714, 0.00616692, 0.07810294, 0.67846367, 0.21325051,
        0.98303949, 0.7225224 , 0.63721044, 0.30152955, 0.30190231,
        0.57924832, 0.55914408, 0.85159648, 0.59263108, 0.02153168,
        0.1845709 , 0.14141198, 0.41392065, 0.53891775],
       [0.85898474, 0.23824428, 0.48891799, 0.93931929, 0.71037652,
        0.0407236 , 0.3661424 , 0.55039545, 0.71604887, 0.14449892,
        0.16016515, 0.60479891, 0.45134698, 0.770128  , 0.98243069,
        0.64831354, 0.03034311, 0.56121632, 0.86371483],
       [0.56284621, 0.5875876 , 0.01593808, 0.34857457, 0.14582675,
        0.43542684, 0.81016007, 0.22887608, 0.93445935, 0.65293776,
        0.65805717, 0.09054904, 0.51924277, 0.98273803, 0.78134044,
        0.21696796, 0.1453332 , 0.14883813, 0.38964431],
       [0.55189035, 0.06562932, 0.00571449, 0.96806299, 0.21445527,
        0.27743083, 0.53460838, 0.88990462, 0.25795717, 0.87501048,
        0.45655656, 0.50191516, 0.53660788, 0.65583622, 0.44578121,
        0.609

In [20]:
# Ejemplo caída paracaídista:

t = np.arange (0, 10.2,0.2) # t[s]
V = ((68.1*0.51)/12.5)*(1-np.exp(-(12.5/68.1)*t))
datos_CP = np.column_stack([t,V])
np.savetxt('Datos_CP.txt',datos_CP, fmt = '%.2f')

In [21]:
# Cargar datos desde un archivo de texto:
M_DCP =  np.genfromtxt('Datos_CP.txt')
M_DCP

array([[ 0.  ,  0.  ],
       [ 0.2 ,  0.1 ],
       [ 0.4 ,  0.2 ],
       [ 0.6 ,  0.29],
       [ 0.8 ,  0.38],
       [ 1.  ,  0.47],
       [ 1.2 ,  0.55],
       [ 1.4 ,  0.63],
       [ 1.6 ,  0.71],
       [ 1.8 ,  0.78],
       [ 2.  ,  0.85],
       [ 2.2 ,  0.92],
       [ 2.4 ,  0.99],
       [ 2.6 ,  1.05],
       [ 2.8 ,  1.12],
       [ 3.  ,  1.18],
       [ 3.2 ,  1.23],
       [ 3.4 ,  1.29],
       [ 3.6 ,  1.34],
       [ 3.8 ,  1.4 ],
       [ 4.  ,  1.45],
       [ 4.2 ,  1.49],
       [ 4.4 ,  1.54],
       [ 4.6 ,  1.58],
       [ 4.8 ,  1.63],
       [ 5.  ,  1.67],
       [ 5.2 ,  1.71],
       [ 5.4 ,  1.75],
       [ 5.6 ,  1.78],
       [ 5.8 ,  1.82],
       [ 6.  ,  1.85],
       [ 6.2 ,  1.89],
       [ 6.4 ,  1.92],
       [ 6.6 ,  1.95],
       [ 6.8 ,  1.98],
       [ 7.  ,  2.01],
       [ 7.2 ,  2.04],
       [ 7.4 ,  2.06],
       [ 7.6 ,  2.09],
       [ 7.8 ,  2.11],
       [ 8.  ,  2.14],
       [ 8.2 ,  2.16],
       [ 8.4 ,  2.18],
       [ 8.

In [22]:
M_DCP.shape

(51, 2)

In [23]:
# Cargas datos discriminando columnas como vectores:

tiempo, velocidad = np.genfromtxt('Datos_CP.txt', unpack=True)

In [24]:
tiempo

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [25]:
velocidad

array([0.  , 0.1 , 0.2 , 0.29, 0.38, 0.47, 0.55, 0.63, 0.71, 0.78, 0.85,
       0.92, 0.99, 1.05, 1.12, 1.18, 1.23, 1.29, 1.34, 1.4 , 1.45, 1.49,
       1.54, 1.58, 1.63, 1.67, 1.71, 1.75, 1.78, 1.82, 1.85, 1.89, 1.92,
       1.95, 1.98, 2.01, 2.04, 2.06, 2.09, 2.11, 2.14, 2.16, 2.18, 2.21,
       2.23, 2.25, 2.27, 2.28, 2.3 , 2.32, 2.34])