***
# Estructuras de datos en Python
***

## Arreglos: Numpy (*Numerical Python*)

In [1]:
import numpy as np

<font color='blue'>**1. Creación:**

In [2]:
# Función array(): Se pasan listas como argumentos:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
datos_1 = [6, 7.5, 8, 0, 1]
a1 = np.array(datos_1)
a1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
a.dtype

dtype('int64')

In [6]:
a1.dtype

dtype('float64')

In [7]:
# Especificación del tipo de datos:
f = np.array([1, 2, 3, 4, 5, 6], dtype=complex)
f

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [8]:
type(f)

numpy.ndarray

In [9]:
f.dtype

dtype('complex128')

In [11]:
# Funciones intrínsecas:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
np.arange(0,1.1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
np.arange(2,-0.1,-0.4)

array([2.0000000e+00, 1.6000000e+00, 1.2000000e+00, 8.0000000e-01,
       4.0000000e-01, 4.4408921e-16])

In [16]:
# Funciones predeterminadas:
b = np.zeros((10))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
b.ndim

1

In [18]:
b.shape

(10,)

In [19]:
len(b)

10

In [20]:
b.size

10

In [21]:
b = np.zeros((1,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
b.ndim

2

In [23]:
b.shape

(1, 10)

In [24]:
b.size

10

In [25]:
c = np.ones((5,1))
c

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [26]:
c.ndim

2

In [27]:
c.shape

(5, 1)

In [28]:
c.size

5

In [30]:
# Arreglos especiales:
v = np.linspace(0,100,16)
v

array([  0.        ,   6.66666667,  13.33333333,  20.        ,
        26.66666667,  33.33333333,  40.        ,  46.66666667,
        53.33333333,  60.        ,  66.66666667,  73.33333333,
        80.        ,  86.66666667,  93.33333333, 100.        ])

In [31]:
len(v)

16

In [36]:
np.logspace(0,6,7)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06])

In [33]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [38]:
# Arreglo con todos los valores iguales:
np.full((17),0.7)

array([0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
       0.7, 0.7, 0.7, 0.7])

In [39]:
np.full((1,17),0.7)

array([[0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
        0.7, 0.7, 0.7, 0.7]])

In [40]:
np.full((7,1),0.7)

array([[0.7],
       [0.7],
       [0.7],
       [0.7],
       [0.7],
       [0.7],
       [0.7]])

In [41]:
# Numeros aleatorios:
np.random.random(4)

array([0.81491877, 0.68574283, 0.10171236, 0.26518877])

In [46]:
np.random.randn(4)

array([-0.42542767, -0.11685921, -0.51439681,  1.42974117])

In [48]:
# Arreglo con números aleatorios entre 0 y 100, inclusive:
np.random.randint(101, size=(20))

array([10,  2, 40, 27, 14,  0, 47, 18, 44,  8, 33, 28,  1, 34, 16, 20, 43,
       27, 39, 43])

In [49]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

<font color='blue'>**2. Operaciones artiméticas:**

In [50]:
# Vectorización: operaciones elmento a elemento, sin necesidad de usar bucles
a = np.arange(4)
a

array([0, 1, 2, 3])

In [51]:
a + 4

array([4, 5, 6, 7])

In [52]:
a * 2

array([0, 2, 4, 6])

In [53]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [54]:
a + b

array([ 4,  6,  8, 10])

<img src="arreglos_op_aritmeticas.png" width="200" height="200">

In [55]:
a - b

array([-4, -4, -4, -4])

In [56]:
a * b

array([ 0,  5, 12, 21])

In [57]:
# Funciones universales:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [58]:
a  * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [61]:
# Incrementos y decrementos:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [62]:
a += 1
a

array([1, 2, 3, 4])

In [63]:
a -= 1
a

array([0, 1, 2, 3])

In [64]:
a *= 2
a

array([0, 2, 4, 6])

<font color='blue'>**3. Comparación de los tiempos de cálculo:**

In [65]:
l = list(range(10000000))
v = np.arange(10000000)

In [66]:
%time for _ in range(10): v = v *2

CPU times: user 249 ms, sys: 229 ms, total: 479 ms
Wall time: 477 ms


In [67]:
%time for _ in range(10): l_1 = [i * 2 for i in l]

CPU times: user 6.61 s, sys: 1.54 s, total: 8.15 s
Wall time: 8.17 s


<font color='blue'>**4. Funciones agregadas:**

In [69]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

In [70]:
a.sum()

15.0

In [71]:
a.min()

0.3

In [72]:
a.max()

5.7

In [73]:
a.mean()

3.0

In [74]:
a.std()

2.0079840636817816

In [75]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

<font color='blue'>**5. Arreglos bidimensionales:**

<img src="arreglos_1D_indexacion.png" width="300" height="300">
<img src="arreglos_2D_indexacion.png" width="200" height="200">

In [93]:
A = np.array([[4, -2, 1],\
              [-2, 4, -2],\
              [1, -2, 3]])
A

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  3]])

In [80]:
v = np.arange(0,12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
v.size

12

In [82]:
len(v)

12

In [83]:
v_m = v.reshape(3, 4)
v_m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
v_m = v.reshape(12, 1)
v_m

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [87]:
A

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  3]])

In [88]:
B = A
B

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  3]])

In [90]:
B[1,1] = 0

In [91]:
B

array([[ 4, -2,  1],
       [-2,  0, -2],
       [ 1, -2,  3]])

In [92]:
A

array([[ 4, -2,  1],
       [-2,  0, -2],
       [ 1, -2,  3]])

In [94]:
# Copiar arreglos
B = np.copy(A)
B

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  3]])

In [95]:
B[1,1] = 0
B

array([[ 4, -2,  1],
       [-2,  0, -2],
       [ 1, -2,  3]])

In [96]:
A

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  3]])

In [97]:
A * A

array([[16,  4,  1],
       [ 4, 16,  4],
       [ 1,  4,  9]])

In [98]:
# Producto matricial / vectorial
np.dot(A,A)

array([[ 21, -18,  11],
       [-18,  24, -16],
       [ 11, -16,  14]])

In [100]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [102]:
np.full((5,9),8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [103]:
C = np.random.randint(101, size=(6,6))
C

array([[45,  4, 40, 54, 84, 13],
       [ 9, 98, 17, 73, 82, 31],
       [51, 70, 58, 44, 37, 76],
       [39, 21, 96, 73,  6, 47],
       [82, 61, 88, 53, 60, 63],
       [93, 40, 82, 80, 89, 87]])

In [105]:
C[1,:]

array([ 9, 98, 17, 73, 82, 31])

In [106]:
C[:,4]

array([84, 82, 37,  6, 60, 89])

In [107]:
C[:,4] = np.zeros(6)

In [108]:
C

array([[45,  4, 40, 54,  0, 13],
       [ 9, 98, 17, 73,  0, 31],
       [51, 70, 58, 44,  0, 76],
       [39, 21, 96, 73,  0, 47],
       [82, 61, 88, 53,  0, 63],
       [93, 40, 82, 80,  0, 87]])

In [109]:
D = C[1:5,1:5].copy()
D

array([[98, 17, 73,  0],
       [70, 58, 44,  0],
       [21, 96, 73,  0],
       [61, 88, 53,  0]])

In [110]:
D[2,2] = -73
D

array([[ 98,  17,  73,   0],
       [ 70,  58,  44,   0],
       [ 21,  96, -73,   0],
       [ 61,  88,  53,   0]])

In [111]:
C

array([[45,  4, 40, 54,  0, 13],
       [ 9, 98, 17, 73,  0, 31],
       [51, 70, 58, 44,  0, 76],
       [39, 21, 96, 73,  0, 47],
       [82, 61, 88, 53,  0, 63],
       [93, 40, 82, 80,  0, 87]])

In [112]:
D

array([[ 98,  17,  73,   0],
       [ 70,  58,  44,   0],
       [ 21,  96, -73,   0],
       [ 61,  88,  53,   0]])

In [119]:
E = np.transpose(D).c

In [120]:
E

array([[ 98,  70,  21,  61],
       [ 17,  58,  96,  88],
       [ 73,  44, -73,  53],
       [  0,   0,   0,   0]])

In [121]:
D

array([[ 98,  17,  73,   0],
       [ 70,  58,  44,   0],
       [ 21,  96, -73,   0],
       [ 61,  88,  53,   0]])

In [122]:
E[0,0] = 100

In [124]:
E = np.transpose(D).copy()

In [125]:
E[0,0] = -5

In [126]:
E

array([[ -5,  70,  21,  61],
       [ 17,  58,  96,  88],
       [ 73,  44, -73,  53],
       [  0,   0,   0,   0]])

In [127]:
D

array([[100,  17,  73,   0],
       [ 70,  58,  44,   0],
       [ 21,  96, -73,   0],
       [ 61,  88,  53,   0]])

In [129]:
F = D.flatten()
F

array([100,  17,  73,   0,  70,  58,  44,   0,  21,  96, -73,   0,  61,
        88,  53,   0])

In [130]:
F[0] = -5

In [131]:
F

array([ -5,  17,  73,   0,  70,  58,  44,   0,  21,  96, -73,   0,  61,
        88,  53,   0])

In [132]:
D

array([[100,  17,  73,   0],
       [ 70,  58,  44,   0],
       [ 21,  96, -73,   0],
       [ 61,  88,  53,   0]])

In [133]:
from time import time

In [134]:
help(time)

Help on built-in function time in module time:

time(...)
    time() -> floating point number
    
    Return the current time in seconds since the Epoch.
    Fractions of a second may be present if the system clock provides them.



In [135]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

In [136]:
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [137]:
b = np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [138]:
a * b

array([ 3.3,  9. ,  3.6, 22.8,  1.5])

In [139]:
np.dot(a,b)

40.2

In [140]:
np.inner(a, b)

40.2

In [142]:
a = np.random.random((1,5))
a

array([[0.4268089 , 0.48123285, 0.76239842, 0.03165042, 0.7865401 ]])

In [143]:
b = np.random.random((5,1))
b

array([[0.40514799],
       [0.79744808],
       [0.45701802],
       [0.53518224],
       [0.8076288 ]])

In [144]:
a * b

array([[0.17292077, 0.19497052, 0.30888418, 0.0128231 , 0.31866514],
       [0.34035794, 0.38375821, 0.60797316, 0.02523957, 0.62722489],
       [0.19505936, 0.21993208, 0.34842981, 0.01446481, 0.359463  ],
       [0.22842054, 0.25754728, 0.4080221 , 0.01693874, 0.42094229],
       [0.34470316, 0.38865751, 0.61573492, 0.02556179, 0.63523243]])

In [145]:
b * a

array([[0.17292077, 0.19497052, 0.30888418, 0.0128231 , 0.31866514],
       [0.34035794, 0.38375821, 0.60797316, 0.02523957, 0.62722489],
       [0.19505936, 0.21993208, 0.34842981, 0.01446481, 0.359463  ],
       [0.22842054, 0.25754728, 0.4080221 , 0.01693874, 0.42094229],
       [0.34470316, 0.38865751, 0.61573492, 0.02556179, 0.63523243]])

In [146]:
np.dot(a,b)

array([[1.55727997]])

In [147]:
np.dot(b,a)

array([[0.17292077, 0.19497052, 0.30888418, 0.0128231 , 0.31866514],
       [0.34035794, 0.38375821, 0.60797316, 0.02523957, 0.62722489],
       [0.19505936, 0.21993208, 0.34842981, 0.01446481, 0.359463  ],
       [0.22842054, 0.25754728, 0.4080221 , 0.01693874, 0.42094229],
       [0.34470316, 0.38865751, 0.61573492, 0.02556179, 0.63523243]])